---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-releases-monitor
  namespace: {{ .Values.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-releases-monitor-role
rules:
  - apiGroups:
      - csye7125.tutorial.kubebuilder.io
    resources:
      - githubreleases
      - githubreleasesmonitors
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - jobs/status
    verbs:
      - create
      - get
      - list
      - watch
      - delete
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-releases-monitor-rolebinding
subjects:
  - kind: ServiceAccount
    name: github-releases-monitor
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: github-releases-monitor-role
  apiGroup: rbac.authorization.k8s.io

