apiVersion: csye7125.tutorial.kubebuilder.io/v1
kind: GitHubReleasesMonitor
metadata:
  name: cve-github-releases-monitor
  namespace: {{ .Values.namespace }}
spec:
  url: "{{ .Values.url }}"
  monitorFrom: "{{ .Values.monitorFrom }}"