---
apiVersion: v1
kind: Namespace
metadata:
  name: operator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: operator
  labels:
    app: operator
spec:
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      imagePullSecrets:
      - name: operatorcred
      containers:
        - name: cve-operator
          image: "{{ .Values.image.name }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /manager
          ports:
            - name: http
              containerPort: 9443
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}

