apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: {{ .Values.namespace }}
  labels:
    app: operator
spec:
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      imagePullSecrets:
      - name: regcred
      serviceAccountName: github-releases-monitor
      containers:
        - name: cve-operator
          image: {{ .Values.image.name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: URL
              value: {{ .Values.url | quote }}
            - name: MONITOR_FROM
              value: {{ .Values.monitorFrom | quote }}
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-access-token
                  key: token
            - name: CONTAINER_IMAGE
              value: {{ .Values.controller.image | quote }}
          ports:
            - name: http
              containerPort: 9443
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}

