apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network-policy
  namespace: operator
spec:
  podSelector:
    matchLabels:
      app: operator
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: operator
      ports:
        - protocol: TCP
          port: 8082
  egress:
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0  
      ports:
        - protocol: TCP
          port: 443 
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0 